logger_name: MiroLogger
log_level: INFO

handlers:
  - type: stream
    formatter:
      format: '[bold red][%(name)s][/bold red] - %(asctime)s - [%(levelname)s] - [bold green]%(message)s[/bold green]'
      date_format: '%Y-%m-%d %H:%M:%S'
  - type: file
    relative_path: './logs'
    max_bytes: "1000000"
    backup_count: 3
    formatter:
      format: '[bold red blink][%(name)s][/]  - %(asctime)s - [%(levelname)s] - [bold blue]%(message)s[/bold blue]'
      date_format: '%Y-%m-%d %H:%M:%S'

levels:
  - name: NOTSET
    logger_name: NotSetLogger
    log_level: NOTSET
    file_path: '../../../logs/notset'

  - name: DEBUG
    logger_name: DebugLogger
    log_level: DEBUG
    file_path: '../../../logs/debug'

  - name: INFO
    logger_name: InfoLogger
    log_level: INFO
    file_path: '../../../logs/info'

  - name: WARNING
    logger_name: WarningLogger
    log_level: WARNING
    file_path: '../../../logs/warning'

  - name: ERROR
    logger_name: ErrorLogger
    log_level: ERROR
    file_path: '../../../logs/error'

  - name: CRITICAL
    logger_name: CriticalLogger
    log_level: CRITICAL
    file_path: '../../../logs/critical'